baseURL = "https://nav-yodhcn.vercel.app/"
languageCode = "zh-CN"
title = "电解熔融氧化铝导航"
theme = "webstack-hugo-2.0rc2"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = "yodhcn"
[params.search]
  enable = false
[params.darkmode]
  enable = false